services:
  web:
    build: 
      context: ./client/.
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    container_name: pomodoro-web
    depends_on:
      - api
    ports:
      - "3001:3000"
    networks:
      - my-network
  api:
    build: ./server/.
    container_name: pomodoro-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: pomodoro_db
    ports:
      - "5433:5432"
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    external: true
