jwt:
  secret: ${JWT_SECRET_KEY:VQirijZUa7yqu1BgAVE4hSvfHsmXDs4LNfI1kItySviK2wX8HRsKqsl40Y+nToFM}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/pomodoro_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
