spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pomodoro_db
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
