version: "3"

services:
  postgres:
    image: postgres
    container_name: pomodoro_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pomodoro_db
    ports:
      - "5433:5432"
